@PREFIX = http://localhost:3001/api
## Authentication
### LOGIN User (Correct)
POST {{PREFIX}}/sessions HTTP/1.1
Content-Type: application/json

{
    "username":"DerKevin1",
    "password":"123"
}
### LOGIN User (Wrong Username)
POST {{PREFIX}}/sessions HTTP/1.1
Content-Type: application/json

{
    "username":"DerKevin0",
    "password":"123"
}

### LOGIN User (Wrong Password)
POST {{PREFIX}}/sessions HTTP/1.1
Content-Type: application/json

{
    "username":"DerKevin1",
    "password":"124"
}

### GET User
GET {{PREFIX}}/sessions/current HTTP/1.1

### DELETE User (from Session, logout)
DELETE {{PREFIX}}/sessions/current  HTTP/1.1

# Gameplay
## Setup
### GET Lines and the respective station-station connections the line covers.
GET {{PREFIX}}/lines HTTP/1.1

### GET Stations
GET {{PREFIX}}/stations HTTP/1.1

## During Game
### GET random starting and destination station with route consisting at least of 3 segments
GET {{PREFIX}}/randstartdest HTTP/1.1

### GET random Event
GET {{PREFIX}}/event HTTP/1.1

## Game End
### POST player highscore (successfully)
POST {{PREFIX}}/highscore HTTP/1.1
Content-Type: application/json

{
    "highscore":"10"
}

### GET player highscores (successfully)
GET {{PREFIX}}/highscores HTTP/1.1
